version: '3.8'

services:
  # Layanan PHP (untuk menjalankan Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  # Layanan Nginx (untuk melayani aplikasi Laravel)
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel-network
    depends_on:
      - app

networks:
  laravel-network:
    driver: bridge
